name: 'GitHub Pages Deployment'

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/gh-pages-deployment.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist