name: 'GitHub Pages Deployment'

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/gh-pages-deployment.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run:  npm run deploy -- -m "Deploy React app to GitHub Pages"